# Generated by Django 4.0.5 on 2022-06-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero',
        ),
    ]
