# Generated by Django 4.0.5 on 2022-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuario_bairro_remove_usuario_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.TextField(blank=True, null=True),
        ),
    ]
