# Generated by Django 4.0.5 on 2022-06-27 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ida', models.DateField()),
                ('dt_volta', models.DateField()),
                ('destino', models.CharField(max_length=100, null=True)),
                ('finalidade', models.CharField(choices=[('L', 'Lazer'), ('N', 'Negócios'), ('E', 'Estudos'), ('O', 'Outros')], default='', max_length=50)),
                ('tipo_passagem', models.CharField(choices=[('A', 'Aérea'), ('T', 'Terrestre'), ('M', 'Matítima')], default='', max_length=50)),
                ('classificacao_hotel', models.IntegerField()),
                ('tipo_pensao', models.CharField(choices=[('CM', 'Café da manhã'), ('MP', 'Meia pensão'), ('PC', 'Pensão Completa'), ('AI', 'All Inclusive')], default='', max_length=50)),
                ('observacoes', models.CharField(blank=True, max_length=300, null=True)),
                ('orcamento', models.CharField(blank=True, max_length=50, null=True)),
                ('qtde_0_6', models.IntegerField()),
                ('qtde_7_12', models.IntegerField()),
                ('qtde_adultos', models.IntegerField()),
                ('qtde_melhor_idade', models.IntegerField()),
                ('transfer', models.BooleanField(default=False)),
                ('seguro_viagem', models.BooleanField(default=False)),
                ('passeios', models.BooleanField(default=False)),
                ('ingressos', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
