# Generated by Django 4.0.5 on 2022-06-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0003_orc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orc',
            name='status',
        ),
    ]
