# Generated by Django 4.0.5 on 2022-06-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0004_remove_orc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orc',
            name='qtde_0_6',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'acima de 5')], default=0),
        ),
    ]
