# Generated by Django 4.0.5 on 2022-06-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0005_alter_orc_qtde_0_6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orc',
            name='qtde_0_6',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'acima de 5')], default=0),
        ),
        migrations.AlterField(
            model_name='orc',
            name='qtde_7_12',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'acima de 5')], default=0),
        ),
        migrations.AlterField(
            model_name='orc',
            name='qtde_adultos',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'acima de 5')], default=0),
        ),
        migrations.AlterField(
            model_name='orc',
            name='qtde_melhor_idade',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', 'acima de 5')], default=0),
        ),
    ]
