# Generated by Django 4.0.5 on 2022-06-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0006_alter_orc_qtde_0_6_alter_orc_qtde_7_12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orc',
            name='qtde_0_6',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orc',
            name='qtde_7_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orc',
            name='qtde_adultos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orc',
            name='qtde_melhor_idade',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
