# Generated by Django 3.2.8 on 2022-06-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0007_alter_orc_qtde_0_6_alter_orc_qtde_7_12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orc',
            name='qtde_0_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orc',
            name='qtde_melhor_idade',
            field=models.IntegerField(default=0),
        ),
    ]
