# Generated by Django 4.0.5 on 2022-06-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0008_auto_20220628_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orc',
            name='classificacao_hotel',
            field=models.CharField(choices=[('1', '1 estrela'), ('2', '2 estrela'), ('3', '3 estrelas'), ('4', '4 estrelas'), ('5', '5 estrelas')], default=3, max_length=12),
        ),
    ]
