# Generated by Django 4.0.5 on 2022-06-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orc',
            name='classificacao_hotel',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='finalidade',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='ingressos',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='orcamento',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='passeios',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='qtde_0_6',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='qtde_7_12',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='qtde_adultos',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='qtde_melhor_idade',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='seguro_viagem',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='tipo_passagem',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='tipo_pensao',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='orc',
            name='usuario',
        ),
    ]
