# Generated by Django 4.0.5 on 2022-06-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0002_remove_orc_classificacao_hotel_remove_orc_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='destino',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
