# Generated by Django 4.0.5 on 2022-06-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0003_orc_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='finalidade',
            field=models.CharField(choices=[('L', 'Lazer'), ('N', 'Negócios'), ('E', 'Estudos'), ('O', 'Outros')], default='', max_length=50),
        ),
    ]
