# Generated by Django 4.0.5 on 2022-06-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0004_orc_finalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='tipo_passagem',
            field=models.CharField(choices=[('A', 'Aérea'), ('T', 'Terrestre'), ('M', 'Matítima')], default='', max_length=50),
        ),
    ]
