# Generated by Django 4.0.5 on 2022-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0005_orc_tipo_passagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orc',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
