# Generated by Django 4.0.5 on 2022-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0006_orc_email_orc_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='orcamento',
            field=models.CharField(blank=True, default='0', max_length=15, null=True),
        ),
    ]
