# Generated by Django 4.0.5 on 2022-06-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0008_alter_orc_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orc',
            name='orcamento',
            field=models.CharField(blank=True, default='R$ ', max_length=15, null=True),
        ),
    ]
