# Generated by Django 4.0.5 on 2022-06-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0009_alter_orc_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='observacoes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
