# Generated by Django 4.0.5 on 2022-06-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0010_orc_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='classificacao_hotel',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2 estrela'), ('3', '3 estrelas'), ('4', '4 estrelas'), ('5', '5 estrelas'), ('6', 'acima de 5')], default=3),
        ),
    ]
