# Generated by Django 4.0.5 on 2022-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0011_orc_classificacao_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orc',
            name='classificacao_hotel',
            field=models.CharField(choices=[('1', '1 estrela'), ('2', '2 estrela'), ('3', '3 estrelas'), ('4', '4 estrelas'), ('5', '5 estrelas'), ('6', 'acima de 5')], default=3, max_length=12),
        ),
    ]
