# Generated by Django 4.0.5 on 2022-06-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0012_alter_orc_classificacao_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='tipo_pensao',
            field=models.CharField(choices=[('CM', 'Café da manhã'), ('MP', 'Meia pensão'), ('PC', 'Pensão Completa'), ('AI', 'All Inclusive')], default='', max_length=50),
        ),
    ]
