# Generated by Django 4.0.5 on 2022-06-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0013_orc_tipo_pensao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='qtde_0_6',
            field=models.IntegerField(default=0),
        ),
    ]
