# Generated by Django 4.0.5 on 2022-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0014_orc_qtde_0_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='qtde_7_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orc',
            name='qtde_adultos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orc',
            name='qtde_melhor_idade',
            field=models.IntegerField(default=0),
        ),
    ]
