# Generated by Django 4.0.5 on 2022-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0015_orc_qtde_7_12_orc_qtde_adultos_orc_qtde_melhor_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
    ]
