# Generated by Django 4.0.5 on 2022-06-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0016_orc_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='seguro_viagem',
            field=models.BooleanField(default=False),
        ),
    ]
