# Generated by Django 4.0.5 on 2022-06-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitaorcamento', '0017_orc_seguro_viagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orc',
            name='ingressos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orc',
            name='passeios',
            field=models.BooleanField(default=False),
        ),
    ]
